// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrVfAFiZDhMzUAe_llu1qLPRUdtiePLY',
    appId: '1:586880281477:web:183ed5c457730fd26c72ec',
    messagingSenderId: '586880281477',
    projectId: 'plant-project-f8caf',
    authDomain: 'plant-project-f8caf.firebaseapp.com',
    storageBucket: 'plant-project-f8caf.appspot.com',
    measurementId: 'G-86Y1PDPW6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKb6AuIw433CAwEC5UspP5KAs3cWCwgSg',
    appId: '1:586880281477:android:f69ed508704efc6b6c72ec',
    messagingSenderId: '586880281477',
    projectId: 'plant-project-f8caf',
    storageBucket: 'plant-project-f8caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWl30tZSxZTZGTrQAtzunvQ4LeNcx-v8',
    appId: '1:586880281477:ios:2b94d3ec867c98446c72ec',
    messagingSenderId: '586880281477',
    projectId: 'plant-project-f8caf',
    storageBucket: 'plant-project-f8caf.appspot.com',
    iosClientId: '586880281477-f2m567vu5oqrtci7fosk95off5knd22m.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWl30tZSxZTZGTrQAtzunvQ4LeNcx-v8',
    appId: '1:586880281477:ios:ff3d2315bbf977d26c72ec',
    messagingSenderId: '586880281477',
    projectId: 'plant-project-f8caf',
    storageBucket: 'plant-project-f8caf.appspot.com',
    iosClientId: '586880281477-lgko5p44uteattp2t71jogm0te3monot.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantsProject.RunnerTests',
  );
}
